server:
  port: 8080
  context-path: /web
  spring:
    mvc:
      view:
        prefix: /templates
        suffix: .html
spring:
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  thymeleaf:
    cache: false
